<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetWindowsVersion>10.0.22000.0</TargetWindowsVersion>
    <CoreFramework>net6.0-windows$(TargetWindowsVersion)</CoreFramework>
    <DesktopFramework>net461</DesktopFramework>
  </PropertyGroup>
  
  <PropertyGroup>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <LangVersion>10</LangVersion>
    <OutputPath>$(SolutionDir)$(Platform)\$(Configuration)\$(MSBuildProjectName)\</OutputPath>
    <Platforms>x64;x86</Platforms>
    <TargetFrameworks>$(CoreFramework);$(DesktopFramework)</TargetFrameworks>
  </PropertyGroup>
  

  <ItemGroup>
    <AdditionalFiles Include="..\stylecop.json" Link="stylecop.json" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.1.0" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector" Version="3.1.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  
  <ItemGroup Condition="'$(TargetFramework)' == '$(CoreFramework)'">
    <PackageReference Include="Microsoft.Windows.CsWinRT" Version="1.6.4" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == '$(DesktopFramework)'">
    <PackageReference Include="Microsoft.Windows.SDK.Contracts" Version="10.0.22000.196" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Microsoft.WinGet.Client\Microsoft.WinGet.Client.csproj" />
  </ItemGroup>

</Project>
